import threading
import time
import traceback
import sys
import random

TICK_DELAY = 3.0
NPC_ACTION_MAX_TEXT_LENGTH = 1000

class Colour:
    UNDERLINE = "\033[4m" # i know, not a colour - but it makes sense here
    BOLD      = "\033[1m"
    DIM       = "\033[2m"

    BOLD_OFF      = "\033[22m"
    ITALIC_OFF    = "\033[23m"
    UNDERLINE_OFF = "\033[24m"
    REVERSE_OFF   = "\033[27m"
    STRIKE_OFF    = "\033[29m"

    RESET = "\033[0m"
    RED = "\033[31m"
    GREEN = "\033[32m"
    YELLOW = "\033[33m"
    BLUE = "\033[34m"
    MAGENTA = "\033[35m"
    CYAN = "\033[36m"
    WHITE = "\033[37m"

    BRIGHT_RED    = "\033[1;91m"
    BRIGHT_GREEN  = "\033[1;92m"
    BRIGHT_YELLOW = "\033[1;93m"
    BRIGHT_BLUE   = "\033[1;94m"
    BRIGHT_MAGENTA= "\033[1;95m"
    BRIGHT_CYAN   = "\033[1;96m"
    BRIGHT_WHITE  = "\033[1;97m"

    TITLE = "\033[1;4;97m"

def colour(text, code):
    return code + text + Colour.RESET

class Entity(object):
    """Base class for things which can exist in the world."""

    def __init__(self, name, description=""):
        self.name = name
        self.description = description

    def look(self, viewer):
        if self.description:
            return self.description
        return "You see nothing remarkable about {0}.".format(self.name)


class Item(Entity):
    """An object which may be carried or equipped."""

    def __init__(self, name, description="", wearable=False, worn_where="Head"):
        Entity.__init__(self, name, description)
        self.wearable = wearable
        self.worn_where = worn_where

    def on_equip(self, player):
        pass

    def describe_look_equip(self, player):
        """Describe the item as a piece of equipment when equipped
        """
        if self.wearable:
           return "%s: %s" % (self.name,self.worn_where)
        else:
           return self.name

    def on_unequip(self, player):
        pass

class Room(object):
    """Base class for a location.

    Rooms are code, so subclasses may add arbitrary state and behaviour.
    """

    def __init__(self, room_id, name, description):
        self.room_id = room_id
        self.name = name
        self.description = description
        self.exits = {}
        self.players = []
        self.npcs = []
        self.items = []
        self.lock = threading.RLock()

    def add_exit(self, direction, destination):
        self.exits[direction.lower()] = destination

    def add_npc(self, npc):
        with self.lock:
            if npc not in self.npcs:
                self.npcs.append(npc)
                NPCManager.instance().register(npc)
                npc.room = self

    def remove_npc(self, npc):
        with self.lock:
            if npc in self.npcs:
                self.npcs.remove(npc)
                NPCManager.instance().unregister(npc)
                npc.room = None

    def enter(self, player, announce=True):
        with self.lock:
            if player not in self.players:
                self.players.append(player)

        player.room = self
        self._notify_npcs("on_player_enter", player)

        if announce:
            self.broadcast(
                "* {0} arrives.".format(player.name),
                exclude=player.session
            )

    def leave(self, player, announce=True):
        # Let NPCs react while the departing player can still receive a
        # farewell generated by the behavior.
        self._notify_npcs("on_player_leave", player)

        with self.lock:
            if player in self.players:
                self.players.remove(player)

        if announce:
            self.broadcast(
                "* {0} leaves.".format(player.name),
                exclude=player.session
            )

    def broadcast(self, message, exclude=None):
        with self.lock:
            recipients = list(self.players)

        for player in recipients:
            session = player.session
            if session is not None and session is not exclude:
                session.send(message)

    def notify_player_said(self, player, text):
        self._notify_npcs("on_say", player, text)

    def notify_player_emoted(self, player, action):
        self._notify_npcs("on_emote", player, action)

    def _notify_npcs(self, method_name, *arguments):
        with self.lock:
            recipients = list(self.npcs)

        for npc in recipients:
            callback = getattr(npc, method_name)

            try:
                callback(*arguments)
            except Exception:
                sys.stderr.write(
                    "NPC event {0} failed for {1}.\n".format(
                        method_name,
                        npc.name
                    )
                )
                traceback.print_exc()

    def describe_to(self, player):
        player.session.send("")
        player.session.send(colour(self.name,Colour.TITLE))
#        player.session.send("-" * len(self.name))
        player.session.send(self.description)

        with self.lock:
            other_players = [
                colour(present.name, Colour.BRIGHT_CYAN)
                for present in self.players
                if present is not player
            ]
            item_names = [colour(item.name, Colour.BRIGHT_GREEN) for item in self.items]

            npc_names = [colour(npc.name, Colour.BRIGHT_CYAN) for npc in self.npcs]

        if npc_names:
           player.session.send("People here: {0}".format(", ".join(other_players + npc_names)) ) 
        elif other_players:
             player.session.send("People here: {0}".format(", ".join(other_players)))

        if item_names:
            player.session.send(
                "Objects here: {0}".format(", ".join(item_names))
            )

        if self.exits:
            player.session.send("Exits:")
            for e in self.exits.keys():
                player.session.send("\t %s" % colour(e,Colour.BRIGHT_WHITE))
        else:
            player.session.send("There are no obvious exits.")

    def on_command(self, session, command, arguments):
        """Allow an individual room to handle custom commands.

        Return True when the room handled the command.
        """
        return False

class Player(Entity):
    def __init__(self, name):
        Entity.__init__(self, name, "A mysterious adventurer.")
        self.session = None
        self.room = None
        self.is_admin = False
        self.inventory = []
        self.equipment = {}
        self.fabulousness = 0

    def find_item(self, name):
        wanted = name.strip().lower()

        for item in self.inventory:
            if item.name.lower() == wanted:
                return item

        return None

    def look(self, viewer):
        lines = [colour(self.name, Colour.BRIGHT_CYAN)]

        if self.fabulousness <= -20:
            lines.append(
                "They somehow make a sack of potatoes look glamorous by comparison."
            )

        elif self.fabulousness < 0:
            lines.append(
                "Fashion appears to have lost a fight with reality."
            )

        elif self.fabulousness == 0:
            lines.append(
                "They look perfectly ordinary. Nothing sparkles."
            )

        elif self.fabulousness < 10:
            lines.append(
                "They seem pleasantly well dressed."
            )

        elif self.fabulousness < 20:
            lines.append(
                "There is a definite air of fabulousness about them."
            )

        elif self.fabulousness < 40:
            lines.append(
                "They radiate fabulousness with almost supernatural confidence."
            )

        elif self.fabulousness < 75:
            lines.append(
                "Looking directly at them requires sunglasses."
            )

        elif self.fabulousness < 100:
            lines.append(
                "Nearby rainbows appear to be taking fashion advice from them."
            )

        else:
            lines.append(
                colour(
                    "WARNING: Fabulousness levels have exceeded all known safety limits.",
                    Colour.MAGENTA
                )
            )
            lines.append(
                "Reality itself seems uncertain whether it is fabulous enough to continue existing."
            )

        if self.equipment.items():
            lines.append("Equipment:")
            for k,v in self.equipment.items():
                lines.append("\t%s" % v.describe_look_equip(self))

        if viewer is self:
            lines.append("")
            lines.append(
                "You admire yourself for a moment. Entirely understandable."
            )

        return "\r\n".join(lines)

class Command(object):
    name = None
    aliases = ()
    
    admin_only = False

    def execute(self, session, arguments):
        raise NotImplementedError()


COMMANDS = {}


def register_command(command_class):
    command = command_class()
    names = [command.name]
    names.extend(command.aliases)

    for name in names:
        COMMANDS[name.lower()] = command

    return command_class


class NPCAction(object):
    """A validated, engine-supported action requested by an NPC behavior."""

    TYPE_SAY = "say"
    TYPE_EMOTE = "emote"
    VALID_TYPES = (TYPE_SAY, TYPE_EMOTE)

    def __init__(self, action_type, text):
        self.action_type = action_type
        self.text = text
        self.validate()

    def validate(self):
        action_type = self.action_type
        text = self.text

        if action_type not in self.VALID_TYPES:
            raise ValueError("unsupported NPC action type")

        if not isinstance(text, str):
            raise TypeError("NPC action text must be a string")

        if not text.strip():
            raise ValueError("NPC action text cannot be empty")

        if len(text) > NPC_ACTION_MAX_TEXT_LENGTH:
            raise ValueError("NPC action text is too long")

        for character in text:
            if ord(character) < 32 or ord(character) == 127:
                raise ValueError("NPC action text contains control characters")

    @classmethod
    def say(cls, text):
        return cls(cls.TYPE_SAY, text)

    @classmethod
    def emote(cls, text):
        return cls(cls.TYPE_EMOTE, text)


class NPCBehavior(object):
    """Base contract for a non-player character's decision logic."""

    MODE_NONE = "none"
    MODE_SIMPLE_RANDOM = "simple_random"
    MODE_FSM = "fsm"
    MODE_LLM_FSM = "llm_fsm"

    mode = MODE_NONE

    def __init__(self):
        self.npc = None

    def bind(self, npc):
        if self.npc is not None and self.npc is not npc:
            raise ValueError("NPC behavior is already bound")

        self.npc = npc

    def unbind(self, npc):
        if self.npc is npc:
            self.npc = None

    def on_player_enter(self, player):
        pass

    def on_player_leave(self, player):
        pass

    def on_say(self, player, text):
        pass

    def on_emote(self, player, action):
        pass

    def tick(self):
        pass


class SimpleRandomBehavior(NPCBehavior):
    """Local random chatter and reactions with no state machine or LLM."""

    mode = NPCBehavior.MODE_SIMPLE_RANDOM

    def __init__(
        self,
        speech=(),
        emotes=(),
        entry_speech=(),
        departure_speech=(),
        speech_replies=(),
        emote_reactions=(),
        minimum_delay=20.0,
        maximum_delay=60.0,
        speech_weight=1.0,
        emote_weight=1.0,
        random_source=None,
        time_source=None
    ):
        NPCBehavior.__init__(self)

        if minimum_delay < 0 or maximum_delay < minimum_delay:
            raise ValueError("invalid random behavior delay range")

        if speech_weight < 0 or emote_weight < 0:
            raise ValueError("random behavior weights cannot be negative")

        self.speech = self._validate_pool(speech)
        self.emotes = self._validate_pool(emotes)
        self.entry_speech = self._validate_pool(entry_speech)
        self.departure_speech = self._validate_pool(departure_speech)
        self.speech_replies = self._validate_pool(speech_replies)
        self.emote_reactions = self._validate_pool(emote_reactions)
        self.minimum_delay = minimum_delay
        self.maximum_delay = maximum_delay
        self.speech_weight = speech_weight
        self.emote_weight = emote_weight
        self.random_source = random_source or random
        self.time_source = time_source or time.time
        self.next_action_time = None

    def _validate_pool(self, values):
        if isinstance(values, str):
            result = (values,)
        else:
            result = tuple(values)

        for text in result:
            NPCAction.say(text)

        return result

    def bind(self, npc):
        NPCBehavior.bind(self, npc)
        self._schedule_next_action()

    def _schedule_next_action(self):
        delay = self.random_source.uniform(
            self.minimum_delay,
            self.maximum_delay
        )
        self.next_action_time = self.time_source() + delay

    def _choose_action(self, action_type, choices):
        if not choices:
            return None

        text = self.random_source.choice(choices)
        return NPCAction(action_type, text)

    def _choose_ambient_action(self):
        can_speak = bool(self.speech) and self.speech_weight > 0
        can_emote = bool(self.emotes) and self.emote_weight > 0

        if not can_speak and not can_emote:
            return None

        if can_speak and not can_emote:
            return self._choose_action(NPCAction.TYPE_SAY, self.speech)

        if can_emote and not can_speak:
            return self._choose_action(NPCAction.TYPE_EMOTE, self.emotes)

        total_weight = self.speech_weight + self.emote_weight
        selection = self.random_source.random() * total_weight

        if selection < self.speech_weight:
            return self._choose_action(NPCAction.TYPE_SAY, self.speech)

        return self._choose_action(NPCAction.TYPE_EMOTE, self.emotes)

    def on_player_enter(self, player):
        return self._choose_action(NPCAction.TYPE_SAY, self.entry_speech)

    def on_player_leave(self, player):
        return self._choose_action(
            NPCAction.TYPE_SAY,
            self.departure_speech
        )

    def on_say(self, player, text):
        return self._choose_action(NPCAction.TYPE_SAY, self.speech_replies)

    def on_emote(self, player, action):
        return self._choose_action(
            NPCAction.TYPE_EMOTE,
            self.emote_reactions
        )

    def tick(self):
        now = self.time_source()

        if now < self.next_action_time:
            return None

        if self.npc.room is None:
            return None

        with self.npc.room.lock:
            room_has_players = bool(self.npc.room.players)

        if not room_has_players:
            return None

        action = self._choose_ambient_action()
        self._schedule_next_action()
        return action




class NPCManager(object):
   _instance = None
   def __init__(self):
       self.npcs                  = []
       self.lock                  = threading.RLock()
       self._ticker_thread        = threading.Thread(target=self._run_ticker_thread)
       self._ticker_thread.daemon = True
       self.running               = False

   @classmethod
   def instance(cls):
       if cls._instance is None:
          cls._instance = cls.__new__(cls)
          cls._instance.__init__()
       return cls._instance

   def register(self, npc):
       with self.lock:
            if npc not in self.npcs:
               self.npcs.append(npc)

   def unregister(self, npc):
       with self.lock:
            if npc in self.npcs:
               self.npcs.remove(npc)

   def tick(self):
       with self.lock:
            active_npcs = list(self.npcs)

       for npc in active_npcs:
            try:
                npc.tick()
            except Exception:
                sys.stderr.write(
                    "NPC tick failed for {0}.\n".format(npc.name)
                )
                traceback.print_exc()

   def _run_ticker_thread(self):
       while self.running:
          time.sleep(TICK_DELAY)
          self.tick()

   def start(self):
       self.running = True
       self._ticker_thread.start()
   
   def stop(self):
       self.running = False
       self._ticker_thread.join()


class NPC(Entity):
    """A living non-player character."""

    def __init__(self, name, description="", behavior=None):
        Entity.__init__(self, name, description)

        self.room = None
        self.flags = set()
        self.keywords = []
        self.inventory = []
        self.behavior = None

        if behavior is None:
            behavior = NPCBehavior()

        self.set_behavior(behavior)

    @property
    def behavior_mode(self):
        return self.behavior.mode

    def set_behavior(self, behavior):
        if not isinstance(behavior, NPCBehavior):
            raise TypeError("behavior must be an NPCBehavior")

        if self.behavior is behavior:
            return

        behavior.bind(self)
        previous_behavior = self.behavior
        self.behavior = behavior

        if previous_behavior is not None:
            previous_behavior.unbind(self)

    def _run_behavior(self, method_name, *arguments):
        callback = getattr(self.behavior, method_name)
        result = callback(*arguments)
        actions = self._normalize_actions(result)

        for action in actions:
            self.perform_action(action)

        return actions

    def _normalize_actions(self, result):
        if result is None:
            return ()

        if isinstance(result, NPCAction):
            return (result,)

        if not isinstance(result, (list, tuple)):
            raise TypeError("NPC behavior must return NPC actions")

        actions = tuple(result)

        for action in actions:
            if not isinstance(action, NPCAction):
                raise TypeError("NPC behavior returned an invalid action")

        return actions

    def perform_action(self, action):
        if not isinstance(action, NPCAction):
            raise TypeError("action must be an NPCAction")

        action.validate()

        if action.action_type == NPCAction.TYPE_SAY:
            self.speak(action.text)
            return

        if action.action_type == NPCAction.TYPE_EMOTE:
            self.emote(action.text)
            return

        raise ValueError("unsupported NPC action type")

    def enter(self, room):
        if self.room is not None:
            self.room.remove_npc(self)

        self.room = room
        room.add_npc(self)

    def on_player_enter(self, player):
        """Called when a player enters the room."""
        return self._run_behavior("on_player_enter", player)

    def on_player_leave(self, player):
        return self._run_behavior("on_player_leave", player)

    def on_say(self, player, text):
        """Player spoke aloud."""
        return self._run_behavior("on_say", player, text)

    def on_emote(self, player, action):
        return self._run_behavior("on_emote", player, action)

    def tick(self):
        """Periodic update."""
        return self._run_behavior("tick")

    def speak(self, text):
        if self.room:
            self.room.broadcast("<{0}> {1}".format(colour(self.name,Colour.BRIGHT_CYAN), text))

    def emote(self, text):
        if self.room:
            self.room.broadcast("* {0} {1}".format(colour(self.name,Colour.BRIGHT_CYAN), text))
