import threading
import time
import traceback
import sys
import random
import math
import unicodedata

TICK_DELAY = 3.0
NPC_ACTION_MAX_TEXT_LENGTH = 1000

class Colour:
    UNDERLINE = "\033[4m" # i know, not a colour - but it makes sense here
    BOLD      = "\033[1m"
    DIM       = "\033[2m"

    BOLD_OFF      = "\033[22m"
    ITALIC_OFF    = "\033[23m"
    UNDERLINE_OFF = "\033[24m"
    REVERSE_OFF   = "\033[27m"
    STRIKE_OFF    = "\033[29m"

    RESET = "\033[0m"
    RED = "\033[31m"
    GREEN = "\033[32m"
    YELLOW = "\033[33m"
    BLUE = "\033[34m"
    MAGENTA = "\033[35m"
    CYAN = "\033[36m"
    WHITE = "\033[37m"

    BRIGHT_RED    = "\033[1;91m"
    BRIGHT_GREEN  = "\033[1;92m"
    BRIGHT_YELLOW = "\033[1;93m"
    BRIGHT_BLUE   = "\033[1;94m"
    BRIGHT_MAGENTA= "\033[1;95m"
    BRIGHT_CYAN   = "\033[1;96m"
    BRIGHT_WHITE  = "\033[1;97m"

    TITLE = "\033[1;4;97m"

def colour(text, code):
    return code + text + Colour.RESET

class Entity(object):
    """Base class for things which can exist in the world."""

    def __init__(self, name, description=""):
        self.name = name
        self.description = description

    def look(self, viewer):
        if self.description:
            return self.description
        return "You see nothing remarkable about {0}.".format(self.name)


class Item(Entity):
    """An object which may be carried or equipped."""

    def __init__(self, name, description="", wearable=False, worn_where="Head"):
        Entity.__init__(self, name, description)
        self.wearable = wearable
        self.worn_where = worn_where

    def on_equip(self, player):
        pass

    def describe_look_equip(self, player):
        """Describe the item as a piece of equipment when equipped
        """
        if self.wearable:
           return "%s: %s" % (self.name,self.worn_where)
        else:
           return self.name

    def on_unequip(self, player):
        pass

class Room(object):
    """Base class for a location.

    Rooms are code, so subclasses may add arbitrary state and behaviour.
    """

    def __init__(self, room_id, name, description, time_source=None):
        self.room_id = room_id
        self.name = name
        self.description = description
        self.exits = {}
        self.players = []
        self.npcs = []
        self.items = []
        self.lock = threading.RLock()
        self.time_source = time_source or time.time
        self.visit_count = 0
        self.interaction_count = 0
        self.last_activity_at = None
        self._departing_players = set()

    def add_exit(self, direction, destination):
        self.exits[direction.lower()] = destination

    def add_npc(self, npc):
        with self.lock:
            if npc not in self.npcs:
                self.npcs.append(npc)
                NPCManager.instance().register(npc)
                npc.room = self

    def remove_npc(self, npc):
        with self.lock:
            if npc in self.npcs:
                self.npcs.remove(npc)
                NPCManager.instance().unregister(npc)
                npc.room = None

    def enter(self, player, announce=True):
        previous_room = player.room

        if previous_room is not None and previous_room is not self:
            previous_room.leave(player, announce=announce)

        with self.lock:
            if player in self.players:
                player.room = self
                return False

            self.players.append(player)
            player.room = self
            self.visit_count += 1
            self.last_activity_at = self.time_source()

        self._notify_npcs("on_player_enter", player)

        if announce:
            self.broadcast(
                "* {0} arrives.".format(player.name),
                exclude=player.session
            )

        return True

    def leave(self, player, announce=True):
        with self.lock:
            if (
                player not in self.players
                or player in self._departing_players
            ):
                return False

            self._departing_players.add(player)

        # Let NPCs react while the departing player can still receive a
        # farewell generated by the behavior.
        try:
            self._notify_npcs("on_player_leave", player)
        finally:
            with self.lock:
                if player in self.players:
                    self.players.remove(player)

                self._departing_players.discard(player)

                if player.room is self:
                    player.room = None

                self.last_activity_at = self.time_source()

        if announce:
            self.broadcast(
                "* {0} leaves.".format(player.name),
                exclude=player.session
            )

        return True

    def is_active(self):
        with self.lock:
            return bool(self.players)

    def activity_snapshot(self):
        with self.lock:
            return {
                "room_id": self.room_id,
                "active": bool(self.players),
                "occupancy": len(self.players),
                "visits": self.visit_count,
                "interactions": self.interaction_count,
                "last_activity_at": self.last_activity_at
            }

    def _record_interaction(self, player):
        with self.lock:
            if player not in self.players:
                return False

            self.interaction_count += 1
            self.last_activity_at = self.time_source()
            return True

    def broadcast(self, message, exclude=None):
        with self.lock:
            recipients = list(self.players)

        for player in recipients:
            session = player.session
            if session is not None and session is not exclude:
                session.send(message)

    def notify_player_said(self, player, text):
        if not self._record_interaction(player):
            return False

        self._notify_npcs("on_say", player, text)
        return True

    def notify_player_emoted(self, player, action):
        if not self._record_interaction(player):
            return False

        self._notify_npcs("on_emote", player, action)
        return True

    def _notify_npcs(self, method_name, *arguments):
        with self.lock:
            recipients = list(self.npcs)

        for npc in recipients:
            callback = getattr(npc, method_name)

            try:
                callback(*arguments)
            except Exception:
                sys.stderr.write(
                    "NPC event {0} failed for {1}.\n".format(
                        method_name,
                        npc.name
                    )
                )
                traceback.print_exc()

    def describe_to(self, player):
        player.session.send("")
        player.session.send(colour(self.name,Colour.TITLE))
#        player.session.send("-" * len(self.name))
        player.session.send(self.description_for(player))

        with self.lock:
            other_players = [
                colour(present.name, Colour.BRIGHT_CYAN)
                for present in self.players
                if present is not player
            ]
            item_names = [colour(item.name, Colour.BRIGHT_GREEN) for item in self.items]

            npc_names = [
                colour(npc.name, Colour.BRIGHT_CYAN)
                for npc in self.npcs
                if "hidden" not in npc.flags
            ]

        if npc_names:
           player.session.send("People here: {0}".format(", ".join(other_players + npc_names)) ) 
        elif other_players:
             player.session.send("People here: {0}".format(", ".join(other_players)))

        if item_names:
            player.session.send(
                "Objects here: {0}".format(", ".join(item_names))
            )

        if self.exits:
            player.session.send("Exits:")
            for e in self.exits.keys():
                player.session.send("\t %s" % colour(e,Colour.BRIGHT_WHITE))
        else:
            player.session.send("There are no obvious exits.")

    def description_for(self, player):
        return self.description

    def on_command(self, session, command, arguments):
        """Allow an individual room to handle custom commands.

        Return True when the room handled the command.
        """
        return False

class Player(Entity):
    def __init__(self, name):
        Entity.__init__(self, name, "A mysterious adventurer.")
        self.session = None
        self.room = None
        self.is_admin = False
        self.inventory = []
        self.equipment = {}
        self.fabulousness = 0

    def find_item(self, name):
        wanted = name.strip().lower()

        for item in self.inventory:
            if item.name.lower() == wanted:
                return item

        return None

    def look(self, viewer):
        lines = [colour(self.name, Colour.BRIGHT_CYAN)]

        if self.fabulousness <= -20:
            lines.append(
                "They somehow make a sack of potatoes look glamorous by comparison."
            )

        elif self.fabulousness < 0:
            lines.append(
                "Fashion appears to have lost a fight with reality."
            )

        elif self.fabulousness == 0:
            lines.append(
                "They look perfectly ordinary. Nothing sparkles."
            )

        elif self.fabulousness < 10:
            lines.append(
                "They seem pleasantly well dressed."
            )

        elif self.fabulousness < 20:
            lines.append(
                "There is a definite air of fabulousness about them."
            )

        elif self.fabulousness < 40:
            lines.append(
                "They radiate fabulousness with almost supernatural confidence."
            )

        elif self.fabulousness < 75:
            lines.append(
                "Looking directly at them requires sunglasses."
            )

        elif self.fabulousness < 100:
            lines.append(
                "Nearby rainbows appear to be taking fashion advice from them."
            )

        else:
            lines.append(
                colour(
                    "WARNING: Fabulousness levels have exceeded all known safety limits.",
                    Colour.MAGENTA
                )
            )
            lines.append(
                "Reality itself seems uncertain whether it is fabulous enough to continue existing."
            )

        if self.equipment.items():
            lines.append("Equipment:")
            for k,v in self.equipment.items():
                lines.append("\t%s" % v.describe_look_equip(self))

        if viewer is self:
            lines.append("")
            lines.append(
                "You admire yourself for a moment. Entirely understandable."
            )

        return "\r\n".join(lines)

class Command(object):
    name = None
    aliases = ()
    
    admin_only = False

    def execute(self, session, arguments):
        raise NotImplementedError()


COMMANDS = {}


def register_command(command_class):
    command = command_class()
    names = [command.name]
    names.extend(command.aliases)

    for name in names:
        COMMANDS[name.lower()] = command

    return command_class


class NPCAction(object):
    """A validated, engine-supported action requested by an NPC behavior."""

    TYPE_SAY = "say"
    TYPE_EMOTE = "emote"
    VALID_TYPES = (TYPE_SAY, TYPE_EMOTE)

    def __init__(self, action_type, text):
        self.action_type = action_type
        self.text = text
        self.validate()

    def validate(self):
        action_type = self.action_type
        text = self.text

        if action_type not in self.VALID_TYPES:
            raise ValueError("unsupported NPC action type")

        if not isinstance(text, str):
            raise TypeError("NPC action text must be a string")

        if not text.strip():
            raise ValueError("NPC action text cannot be empty")

        if len(text) > NPC_ACTION_MAX_TEXT_LENGTH:
            raise ValueError("NPC action text is too long")

        for character in text:
            if unicodedata.category(character) in ("Cc", "Cf", "Cs"):
                raise ValueError("NPC action text contains control characters")

    @classmethod
    def say(cls, text):
        return cls(cls.TYPE_SAY, text)

    @classmethod
    def emote(cls, text):
        return cls(cls.TYPE_EMOTE, text)


class NPCBehavior(object):
    """Base contract for a non-player character's decision logic."""

    MODE_NONE = "none"
    MODE_SIMPLE_RANDOM = "simple_random"
    MODE_FSM = "fsm"
    MODE_LLM_FSM = "llm_fsm"

    mode = MODE_NONE

    def __init__(self):
        self.npc = None

    def bind(self, npc):
        if self.npc is not None and self.npc is not npc:
            raise ValueError("NPC behavior is already bound")

        self.npc = npc

    def unbind(self, npc):
        if self.npc is npc:
            self.npc = None

    def on_player_enter(self, player):
        pass

    def on_player_leave(self, player):
        pass

    def on_say(self, player, text):
        pass

    def on_emote(self, player, action):
        pass

    def tick(self):
        pass


class SimpleRandomBehavior(NPCBehavior):
    """Local random chatter and reactions with no state machine or LLM."""

    mode = NPCBehavior.MODE_SIMPLE_RANDOM

    def __init__(
        self,
        speech=(),
        emotes=(),
        entry_speech=(),
        departure_speech=(),
        speech_replies=(),
        emote_reactions=(),
        minimum_delay=20.0,
        maximum_delay=60.0,
        speech_weight=1.0,
        emote_weight=1.0,
        random_source=None,
        time_source=None
    ):
        NPCBehavior.__init__(self)

        if minimum_delay < 0 or maximum_delay < minimum_delay:
            raise ValueError("invalid random behavior delay range")

        if speech_weight < 0 or emote_weight < 0:
            raise ValueError("random behavior weights cannot be negative")

        self.speech = self._validate_pool(speech)
        self.emotes = self._validate_pool(emotes)
        self.entry_speech = self._validate_pool(entry_speech)
        self.departure_speech = self._validate_pool(departure_speech)
        self.speech_replies = self._validate_pool(speech_replies)
        self.emote_reactions = self._validate_pool(emote_reactions)
        self.minimum_delay = minimum_delay
        self.maximum_delay = maximum_delay
        self.speech_weight = speech_weight
        self.emote_weight = emote_weight
        self.random_source = random_source or random
        self.time_source = time_source or time.time
        self.next_action_time = None

    def _validate_pool(self, values):
        if isinstance(values, str):
            result = (values,)
        else:
            result = tuple(values)

        for text in result:
            NPCAction.say(text)

        return result

    def bind(self, npc):
        NPCBehavior.bind(self, npc)
        self._schedule_next_action()

    def _schedule_next_action(self):
        delay = self.random_source.uniform(
            self.minimum_delay,
            self.maximum_delay
        )
        self.next_action_time = self.time_source() + delay

    def _choose_action(self, action_type, choices):
        if not choices:
            return None

        text = self.random_source.choice(choices)
        return NPCAction(action_type, text)

    def _choose_ambient_action(self):
        can_speak = bool(self.speech) and self.speech_weight > 0
        can_emote = bool(self.emotes) and self.emote_weight > 0

        if not can_speak and not can_emote:
            return None

        if can_speak and not can_emote:
            return self._choose_action(NPCAction.TYPE_SAY, self.speech)

        if can_emote and not can_speak:
            return self._choose_action(NPCAction.TYPE_EMOTE, self.emotes)

        total_weight = self.speech_weight + self.emote_weight
        selection = self.random_source.random() * total_weight

        if selection < self.speech_weight:
            return self._choose_action(NPCAction.TYPE_SAY, self.speech)

        return self._choose_action(NPCAction.TYPE_EMOTE, self.emotes)

    def on_player_enter(self, player):
        return self._choose_action(NPCAction.TYPE_SAY, self.entry_speech)

    def on_player_leave(self, player):
        return self._choose_action(
            NPCAction.TYPE_SAY,
            self.departure_speech
        )

    def on_say(self, player, text):
        return self._choose_action(NPCAction.TYPE_SAY, self.speech_replies)

    def on_emote(self, player, action):
        return self._choose_action(
            NPCAction.TYPE_EMOTE,
            self.emote_reactions
        )

    def tick(self):
        now = self.time_source()

        if now < self.next_action_time:
            return None

        npc = self.npc

        if npc is None:
            return None

        room = npc.room

        if room is None:
            return None

        with room.lock:
            room_has_players = npc.room is room and bool(room.players)

        if not room_has_players:
            return None

        action = self._choose_ambient_action()
        self._schedule_next_action()
        return action


class FSMBehavior(NPCBehavior):
    """A validated finite-state machine described by ordinary data."""

    mode = NPCBehavior.MODE_FSM

    EVENT_PLAYER_ENTER = "player_enter"
    EVENT_PLAYER_LEAVE = "player_leave"
    EVENT_SAY = "say"
    EVENT_EMOTE = "emote"
    EVENT_TICK = "tick"

    VALID_EVENTS = (
        EVENT_PLAYER_ENTER,
        EVENT_PLAYER_LEAVE,
        EVENT_SAY,
        EVENT_EMOTE,
        EVENT_TICK
    )

    STATE_KEYS = ("on_enter", "on_exit", "events", "timeout")
    TRANSITION_KEYS = ("target", "actions", "condition", "handler")
    TIMEOUT_KEYS = (
        "after",
        "target",
        "actions",
        "condition",
        "handler"
    )

    def __init__(self, states, initial_state, time_source=None):
        NPCBehavior.__init__(self)

        self.time_source = time_source or time.time
        self.states = self._validate_states(states)

        if initial_state not in self.states:
            raise ValueError("initial FSM state does not exist")

        self.initial_state = initial_state
        self.current_state = initial_state
        self.entered_state_at = None
        self.next_transition_time = None
        self._pending_actions = ()
        self._state_lock = threading.RLock()

    def _validate_states(self, states):
        if not isinstance(states, dict) or not states:
            raise ValueError("FSM states must be a non-empty dictionary")

        state_names = set(states.keys())
        normalized = {}

        for state_name, definition in states.items():
            if not isinstance(state_name, str) or not state_name:
                raise ValueError("FSM state names must be non-empty strings")

            if not isinstance(definition, dict):
                raise TypeError("FSM state definitions must be dictionaries")

            unknown_keys = set(definition.keys()) - set(self.STATE_KEYS)

            if unknown_keys:
                raise ValueError("unsupported FSM state setting")

            events = definition.get("events", {})

            if not isinstance(events, dict):
                raise TypeError("FSM events must be a dictionary")

            normalized_events = {}

            for event_name, transitions in events.items():
                if event_name not in self.VALID_EVENTS:
                    raise ValueError("unsupported FSM event")

                normalized_events[event_name] = self._validate_transitions(
                    transitions,
                    state_names
                )

            timeout_delay = None
            timeout_transition = None
            timeout = definition.get("timeout")

            if timeout is not None:
                if not isinstance(timeout, dict):
                    raise TypeError("FSM timeout must be a dictionary")

                unknown_timeout_keys = (
                    set(timeout.keys()) - set(self.TIMEOUT_KEYS)
                )

                if unknown_timeout_keys or "after" not in timeout:
                    raise ValueError("invalid FSM timeout definition")

                timeout_delay = self._validate_delay(timeout["after"])
                timeout_definition = dict(timeout)
                del timeout_definition["after"]
                timeout_transition = self._validate_transition(
                    timeout_definition,
                    state_names
                )

            normalized[state_name] = {
                "on_enter": self._validate_actions(
                    definition.get("on_enter", ())
                ),
                "on_exit": self._validate_actions(
                    definition.get("on_exit", ())
                ),
                "events": normalized_events,
                "timeout_delay": timeout_delay,
                "timeout_transition": timeout_transition
            }

        return normalized

    def _validate_delay(self, delay):
        if isinstance(delay, bool) or not isinstance(delay, (int, float)):
            raise TypeError("FSM timeout delay must be a number")

        if delay < 0 or not math.isfinite(delay):
            raise ValueError("FSM timeout delay must be finite and non-negative")

        return float(delay)

    def _validate_actions(self, actions):
        if actions is None:
            return ()

        if isinstance(actions, NPCAction):
            actions = (actions,)

        if not isinstance(actions, (list, tuple)):
            raise TypeError("FSM actions must be NPCAction instances")

        result = tuple(actions)

        for action in result:
            if not isinstance(action, NPCAction):
                raise TypeError("FSM actions must be NPCAction instances")

            action.validate()

        return result

    def _validate_transitions(self, transitions, state_names):
        if isinstance(transitions, dict):
            transitions = (transitions,)

        if not isinstance(transitions, (list, tuple)) or not transitions:
            raise ValueError("FSM event needs at least one transition")

        return tuple(
            self._validate_transition(transition, state_names)
            for transition in transitions
        )

    def _validate_transition(self, transition, state_names):
        if not isinstance(transition, dict):
            raise TypeError("FSM transitions must be dictionaries")

        unknown_keys = set(transition.keys()) - set(self.TRANSITION_KEYS)

        if unknown_keys:
            raise ValueError("unsupported FSM transition setting")

        target = transition.get("target")

        if target is not None and target not in state_names:
            raise ValueError("FSM transition target does not exist")

        condition = transition.get("condition")

        if condition is not None and not callable(condition):
            raise TypeError("FSM transition condition must be callable")

        handler = transition.get("handler")

        if handler is not None and not callable(handler):
            raise TypeError("FSM transition handler must be callable")

        return {
            "target": target,
            "actions": self._validate_actions(
                transition.get("actions", ())
            ),
            "condition": condition,
            "handler": handler
        }

    def bind(self, npc):
        NPCBehavior.bind(self, npc)

        with self._state_lock:
            self.current_state = self.initial_state
            self.entered_state_at = self.time_source()
            self._pending_actions = self.states[
                self.current_state
            ]["on_enter"]
            self._schedule_timeout()

    def _schedule_timeout(self):
        state = self.states[self.current_state]
        delay = state["timeout_delay"]

        if delay is None:
            self.next_transition_time = None
        else:
            self.next_transition_time = self.time_source() + delay

    def set_state(self, state_name, queue_entry_actions=False):
        if state_name not in self.states:
            raise ValueError("FSM state does not exist")

        with self._state_lock:
            self.current_state = state_name
            self.entered_state_at = self.time_source()

            if queue_entry_actions:
                self._pending_actions = self.states[
                    state_name
                ]["on_enter"]
            else:
                self._pending_actions = ()

            self._schedule_timeout()

    def _room_is_active(self):
        npc = self.npc

        if npc is None:
            return False

        room = npc.room

        if room is None:
            return False

        with room.lock:
            return npc.room is room and bool(room.players)

    def _transition_matches(self, transition, context):
        condition = transition["condition"]

        if condition is None:
            return True

        return bool(condition(self, context))

    def _apply_transition(self, transition, context, timed=False):
        actions = list(self._pending_actions)
        self._pending_actions = ()

        if not self._transition_matches(transition, context):
            if timed:
                self._schedule_timeout()
            return tuple(actions), False

        target = transition["target"]
        handler = transition["handler"]

        if handler is not None:
            actions.extend(
                self._validate_actions(handler(self, context))
            )

        if target is None:
            actions.extend(transition["actions"])

            if timed:
                self._schedule_timeout()

            return tuple(actions), True

        old_state = self.states[self.current_state]
        actions.extend(old_state["on_exit"])
        actions.extend(transition["actions"])
        self.current_state = target
        self.entered_state_at = self.time_source()
        new_state = self.states[self.current_state]
        actions.extend(new_state["on_enter"])
        self._schedule_timeout()
        return tuple(actions), True

    def _handle_event(self, event_name, player=None, text=None):
        context = {
            "event": event_name,
            "player": player,
            "text": text
        }

        with self._state_lock:
            transitions = self.states[
                self.current_state
            ]["events"].get(event_name, ())

            if not transitions:
                actions = self._pending_actions
                self._pending_actions = ()
                return actions

            prefix = self._pending_actions
            self._pending_actions = ()

            for transition in transitions:
                actions, matched = self._apply_transition(
                    transition,
                    context
                )

                if matched:
                    return prefix + actions

            return prefix

    def on_player_enter(self, player):
        return self._handle_event(self.EVENT_PLAYER_ENTER, player=player)

    def on_player_leave(self, player):
        return self._handle_event(self.EVENT_PLAYER_LEAVE, player=player)

    def on_say(self, player, text):
        return self._handle_event(
            self.EVENT_SAY,
            player=player,
            text=text
        )

    def on_emote(self, player, action):
        return self._handle_event(
            self.EVENT_EMOTE,
            player=player,
            text=action
        )

    def tick(self):
        if not self._room_is_active():
            return None

        with self._state_lock:
            now = self.time_source()
            state = self.states[self.current_state]

            if (
                self.next_transition_time is not None
                and now >= self.next_transition_time
            ):
                context = {
                    "event": "timeout",
                    "player": None,
                    "text": None
                }
                actions, matched = self._apply_transition(
                    state["timeout_transition"],
                    context,
                    timed=True
                )
                return actions

        return self._handle_event(self.EVENT_TICK)

    def state_snapshot(self):
        with self._state_lock:
            return {
                "state": self.current_state,
                "entered_state_at": self.entered_state_at,
                "next_transition_time": self.next_transition_time
            }




class NPCManager(object):
   _instance = None
   def __init__(self):
       self.npcs                  = []
       self.lock                  = threading.RLock()
       self._ticker_thread        = None
       self._stop_event           = threading.Event()
       self.running               = False

   @classmethod
   def instance(cls):
       if cls._instance is None:
          cls._instance = cls.__new__(cls)
          cls._instance.__init__()
       return cls._instance

   def register(self, npc):
       with self.lock:
            if npc not in self.npcs:
               self.npcs.append(npc)

   def unregister(self, npc):
       with self.lock:
            if npc in self.npcs:
               self.npcs.remove(npc)

   def _npc_is_active(self, npc):
       room = npc.room

       if room is None:
           return False

       with room.lock:
           return (
               npc.room is room
               and npc in room.npcs
               and bool(room.players)
           )

   def active_npcs_snapshot(self):
       with self.lock:
            candidates = list(self.npcs)

       return tuple(
           npc
           for npc in candidates
           if self._npc_is_active(npc)
       )

   def tick(self):
       for npc in self.active_npcs_snapshot():
            if not self._npc_is_active(npc):
                continue

            try:
                npc.tick()
            except Exception:
                sys.stderr.write(
                    "NPC tick failed for {0}.\n".format(npc.name)
                )
                traceback.print_exc()

   def _run_ticker_thread(self):
       while not self._stop_event.wait(TICK_DELAY):
          with self.lock:
              if not self.running:
                  break

          self.tick()

   def start(self):
       with self.lock:
           if self.running:
               return False

           if (
               self._ticker_thread is not None
               and self._ticker_thread.is_alive()
           ):
               return False

           self._stop_event.clear()
           ticker_thread = threading.Thread(
               target=self._run_ticker_thread
           )
           ticker_thread.daemon = True
           self._ticker_thread = ticker_thread
           self.running = True

           try:
               ticker_thread.start()
           except Exception:
               self.running = False
               self._stop_event.set()
               raise

       return True
   
   def stop(self, timeout=None):
       with self.lock:
           self.running = False
           ticker_thread = self._ticker_thread

       self._stop_event.set()

       if ticker_thread is None or not ticker_thread.is_alive():
           return

       if ticker_thread is threading.current_thread():
           return

       if timeout is None:
           timeout = TICK_DELAY + 1.0

       ticker_thread.join(timeout)

       if ticker_thread.is_alive():
           sys.stderr.write(
               "NPC ticker did not stop within {0:.1f} seconds.\n".format(
                   timeout
               )
           )


class NPC(Entity):
    """A living non-player character."""

    def __init__(self, name, description="", behavior=None):
        Entity.__init__(self, name, description)

        self.room = None
        self.flags = set()
        self.keywords = []
        self.inventory = []
        self.behavior = None

        if behavior is None:
            behavior = NPCBehavior()

        self.set_behavior(behavior)

    @property
    def behavior_mode(self):
        return self.behavior.mode

    def set_behavior(self, behavior):
        if not isinstance(behavior, NPCBehavior):
            raise TypeError("behavior must be an NPCBehavior")

        if self.behavior is behavior:
            return

        behavior.bind(self)
        previous_behavior = self.behavior
        self.behavior = behavior

        if previous_behavior is not None:
            previous_behavior.unbind(self)

    def _run_behavior(self, method_name, *arguments):
        callback = getattr(self.behavior, method_name)
        result = callback(*arguments)
        actions = self._normalize_actions(result)

        for action in actions:
            self.perform_action(action)

        return actions

    def _normalize_actions(self, result):
        if result is None:
            return ()

        if isinstance(result, NPCAction):
            return (result,)

        if not isinstance(result, (list, tuple)):
            raise TypeError("NPC behavior must return NPC actions")

        actions = tuple(result)

        for action in actions:
            if not isinstance(action, NPCAction):
                raise TypeError("NPC behavior returned an invalid action")

        return actions

    def perform_action(self, action):
        if not isinstance(action, NPCAction):
            raise TypeError("action must be an NPCAction")

        action.validate()

        if action.action_type == NPCAction.TYPE_SAY:
            self.speak(action.text)
            return

        if action.action_type == NPCAction.TYPE_EMOTE:
            self.emote(action.text)
            return

        raise ValueError("unsupported NPC action type")

    def enter(self, room):
        if self.room is not None:
            self.room.remove_npc(self)

        self.room = room
        room.add_npc(self)

    def on_player_enter(self, player):
        """Called when a player enters the room."""
        return self._run_behavior("on_player_enter", player)

    def on_player_leave(self, player):
        return self._run_behavior("on_player_leave", player)

    def on_say(self, player, text):
        """Player spoke aloud."""
        return self._run_behavior("on_say", player, text)

    def on_emote(self, player, action):
        return self._run_behavior("on_emote", player, action)

    def tick(self):
        """Periodic update."""
        return self._run_behavior("tick")

    def speak(self, text):
        if self.room:
            self.room.broadcast("<{0}> {1}".format(colour(self.name,Colour.BRIGHT_CYAN), text))

    def emote(self, text):
        if self.room:
            self.room.broadcast("* {0} {1}".format(colour(self.name,Colour.BRIGHT_CYAN), text))
